main: net.notfab.hubbasics.spigot.HubBasics
version: '${VERSION}'
name: HubBasics
authors: [Fabricio20]
softdepend: [Multiverse-Core, PlaceholderAPI, NBTAPI]
api-version: '1.13'
load: POSTWORLD
description: >
  HubBasics is a plugin containing settings, options and features you as a server owner might desire.
commands: