name: HubBasics
version: 1.9.9
main: me.Fabricio20.Main
depend: [BarAPI]
commands:
  plugins:
    description: List the server plugins.
    aliases: pl
  hub:
    description: Teleports you back to hub.
  lobby:
    description: Teleports you back to hub.
  sethub:
    description: Sets the Hub location
  hat:
    description: Changes your hat!