###############################
#    HubBasics Config File    #
###############################
#
DisableJoinMessage: false
#Sets if the plugin should disable the join message;
SilentOpJoin: false
#Sets if when a OP join the server, no join message will happen ( Only If DisableJoinMessage = false );
JoinMessage: '&8[&cHubBasics&8] &eWelcome &a%p &eto the server!'
#Sets the join message here (Only if DisableJoinMessage = false);
DisableLeaveMessage: false
#Sets if the plugin should disable the leave message;
SilentOpLeave: false
#Sets if when a OP leave the server, no leave message will happen ( Only If DisableLeaveMessage = false );
LeaveMessage: '&8[&cHubBasics&8] &a%p &eLeft!'
#Sets the leave message here (Only if DisableLeaveMessage = false);
DisableRain: false
#Sets if it's not possible to change the weather ( WARNING: Be Sure That It's Not Raining When Setting Up This );
DisableVoidFall: true
#Sets if when a player falls on void, he gets teleported back to spawn;
VoidFallMsg: '&8[&cHubBasics&8] &a%p &eYou were teleported back to spawn!'
#The message sent to the player that he got teleported back to spawn ( Only if DisableVoidFall = true );
CustomMotd: true
#Sets if the plugin should handle the server MOTD;
2Motds: true
#Sets if the MOTD will use the second MOTD too;
MOTD1: 'Edit this MOTD in the Config! MOTD1'
#Set The MOTD1 ( Only if CustomMotd = true );
MOTD2: 'Edit this MOTD in the Config! MOTD2'
#Set The MOTD2 ( Only if CustomMotd = true and 2Motds = true );
UseAnnouncer: true
#Sets if the Announcer Will Be Enabled ;);
ChatAnnouncerMsg1: '&8[&cHubBasics&8] &e1st announce message!'
ChatAnnouncerMsg2: '&8[&cHubBasics&8] &e2nd announce message!'
ChatAnnouncerMsg3: '&8[&cHubBasics&8] &e3rd announce message!'
ChatAnnouncerMsg4: '&8[&cHubBasics&8] &e4th announce message!'
ChatAnnouncerMsg5: '&8[&cHubBasics&8] &e5th announce message!'
#Sets here the announcer messages ( Null = will not happen );
BossAnnouncerMsg1: 'Boss1'
BossAnnouncerMsg2: 'Boss2'
BossAnnouncerMsg3: 'Boss3'
BossAnnouncerMsg4: 'Boss4'
BossAnnouncerMsg5: 'Boss5'
#Sets here the boss announcer messages ( Null = will not happen );
FakePlugins: '&fPlugins <5>: &aEssentials&f, &aWorldGuard&f, &aWorldEdit&f, &aHubBasics&f, &aChestCommands'
#Set here the message that will appear to the player when /plugins or /pl is typed;
DoubleJump: true
#Set here if DoubleJump will be enabled;
WebSiteLink: 'http://google.com'
ClickHereTo: 'Click Here To'
SeeOurSiteLink: 'See Our Site'
#Sets Here The [Website] Sign Message;
TeamSpeakIP: '192.168.0.1'
ClickHereToTS: 'Click Here To'
SeeOurTSIP: 'See Our TS3 Ip'
#Sets Here The [TS3] Sign Message;
WebSiteMessage: '&8[&cHubBasics&8] &9WebSite: http://example.com'
#Sets here the message that will appears when an user clicks on the WebSite Sign;
TS3Message: '&8[&cHubBasics&8] &9TS3: talk.example.com'
#Sets here the message that will appears when an user clicks on the TS3 Sign;
Prefix: '&8[&cHubBasics&8] '
#Sets Here The Main Prefix For Some Messages.;
HatSet: '&cEnjoy your new hat!'
#Sets here the message that will appears when a hat is sucefully set;
BungeeCord: false
#Sets if bungeecord support will be enabled;
BungeeCordConfig:
  LobbyServer: 'lobby'
  #The Lobby server name ( CASE SENSITIVE );

#Configure the bungeecord support here;
JumpPadBlock: 'REDSTONE_BLOCK'
#Sets here the JumpPad Block ( MUST BE PERFECTLY A MATERIAL FROM BUKKIT ) [Materials: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html ];
KeepFood: true
#Sets if the plugin should keep the food level of the player at maximum level;
KeepHealth: true
#Sets if the plugin should keep the health of the player at maximum level;
HubAtLogin: false
#Sets if the player should go to hub when they login ( No BungeeCord Support [ If u want to use BC, in BC config set force_default_server to true ] );
Stacker: true
#Sets if the stacker should be used ;) [ Stacker Mini-Game, To Avoid Being Stacked Add The Permission HubBasics.NonStackable ];
JoinItems: false
#Sets if the plugin will give custom itens on join [ CAUTION: EXTREMLY BUGGED ] To Edit The Itens Open HubBasics.jar With Winrar And Edit Items.yml;
NoDrops: false
#Set true to disable item drops.
NoDeathDrops: false
#Set true to disable item drops on death.
1.8Fix: false
#Disable Boss Announcer Here [ For 1.8 Servers ]