#########################################
#  Hub-Basics Config Explaination File  #
#########################################
/**
* Created by @Fabricio20.
*/
JoinEvents: # Here are listed the events that happen when a player joins the server.
  DisableMessage: false # Here you can set if the Join Message will appear or not.
  SilentOpJoin: false # Here you can set if you want to players with OP doesnt have a join message.
  Message: '&8[&cHubBasics&8] &eWelcome &a%p &eto the server!' # Here you can configure your custom join message if enabled.
  HubAtLogin: false # Here you can configure if the player will be teleported to the hub on join.
  BossBarOnJoin: false # Here you can configure if the BossBarAnnouncer system will display the boss bar on join.
#
LeaveEvents: # Here are listed the events that happen when a player leaves the server.
  DisableLeaveMessage: false # Here you can set if the Leave Message will appear or not.
  SilentOpLeave: false # Here you can set if you want to players with OP doesnt have a leave message.
  Message: '&8[&cHubBasics&8] &a%p &eLeft!' # Here you can configure your custom leave message if enabled.
#
VoidFall: # Here are listed the events that happen when a player falls on void.
  Enabled: true # If true, this will prevent the player from falling on void.
  Message: '&8[&cHubBasics&8] &a%p &eYou were teleported back to spawn' # The message that is sent to the player when the plugin saves him from void.
#
MotdSystem: # Here you can configure your server's .
  CustomMotd: true # If true, a custom motd will be used.
  MoreMotds: false # If true, more than one motd's can be used.
  Motds: # The Motds you want are listed here. Remember: You can use COLOR CODES + \n ( To change to the second line ).
  - '&cThis is a default motd! Change it in the config.'
#
ChatAnnouncer: # Here you can configure the chat announcer system.
  Enabled: true # If true the chat announcing system will be used.
  Msgs: # The messages you want are listed here. Remember: You can use COLOR CODES.
  - Announce 1
  - Announce 2
  Perworld: false # Here you can configure if you want to limit the Chat Announcer per world.
  Worlds: # Here the words you want to enable the Chat Announcer if Perworld = true;
  - Example
  Time: 60 # Here you can se the time for the message to appear ( In Seconds );
#
BossAnnouncer: # Here you can configure the boss announcer system.
  Enabled: false # If true the boss announcing system will be used. !!WARNING!! to use this you NEED to have BarAPI installed on your server.
  Msgs: # The messages you want are listed here. Remember: You can use COLOR CODES.
  - Announce 1
  - Announce 2
  Perworld: false # Here you can configure if you want to limit the Boss Announcer per world.
  Worlds:  # Here the words you want to enable the Boss Announcer if Perworld = true;
  - Example
  Time: 60 # Here you can se the time for the message to appear ( In Seconds );
#
ActionAnnouncer: # Here you can configure the Action announcer system.
  Enabled: false # If true the Action announcing system will bee enabled
  Msgs: # The messages you want are listed here. Remember: You can use COLOR CODES.
  - Announce 1
  - Announce 2
  Perworld: false # Here you can configure if you want to limit the Action Announcer per world.
  Worlds: # Here the words you want to enable the Action Announcer if Perworld = true;
  - Example
  Time: 3 # Here you can se the time for the message to appear ( In Seconds );
#
FakePlugins: # Here you can configure the Fake Plugin message.
  Enabled: true # If true the /plugins and /pl will display a fake message to players that doesn't have the right permission.
  Msg: '&fPlugins (5): &aYou&f, &aCannot&f, &aSee&f, &aThe&f, &aPlugins' # The custom message that will be displayed. Remember: You can use COLOR CODES.
#
BungeeCord: # BungeeCord configuration area.
  Enabled: false # If BungeeCord support will be enabled.
  LobbyServer: lobby # The default "lobby" server.
#
MagicClock: # Magic Clock Configuration
  Enabled: true # If true the Magic Clock will be enabled. ( Will Give The Clock To The Player )
  EnabledInChest: false # If the magic clock will be avaliable on the /settings chest
  IgnoreBypass: false # If true the Bypass permission for magic clock will be ignored
  Slot: 5 # The Slot Of the Magic Clock
  AllowMove: false # If the item should be allowed to move.
  NoDrop: false # If false the player cannot drop the item.
  Cooldown: 12 # Cooldown for using the clock.
  GiveOnWorldChange: false #If the Clock will be given on world change.
#
TitleSystem: # 1.8 Titles Configuration
  Enabled: true # If the Join Title Will Be Enabled
  Title: '&cThis Is A Title!' # The Title That Will Be Displayed On Join.
  Subtitle: '&9This is a Sub-Title!' # The Subtitle That Will Be Displayed On Join.
#
BookSystem: # Book System Configuration
  Enabled: false # If the book will be given on join.
  Author: HubBasics # The Book Author.
  Name: '&cTha Book' # The Book Name
  Slot: 5 # The Slot That The Book Will Be Given.
  Lore: # The Book Lore
  - '&bTha lore&c.'
  Pages: # The Book Pages
  - '&cThis is a page.'
#
TabList: # Tab List Customization System Configuration
  Enabled: false # If true, customizable tab list will be used.
  Header: '&cWelcome %p!' # Tab List Header.
  Footer: '&aBuy &bViP &aOn Our Website!' # Tab List Footer.
#
HatSystem: # Hat System Configuration
  Enabled: true # If true the /hat command will be enabled
  Name: '&aJust A Hat!' # The hat name
  Lore: # The Hat Lore
  - '&bTha lore&c.'
  Set: '&cEnjoy your new hat!' # The Hat Set Message
  Removed: '&cYour Hat Was Removed!' # The Hat Removed Message
  HatAllowMove: false # If true the hat will be allowed to move
  AllowDrops: true # If true the hat can be dropped
  NoPerm: '&cYou do not have permission for this hat!' # No Permission For Hat Message
#
ChatSystem: # Here you can configure your chat, this option only works with pex for now
  Enabled: true # If true the custom chat will be enabled
  PerWorld: false # If true the chat will be separated per world.
  AllowColors: true # If true people with permission will be able to use chat colors. (HubBasics.ChatColor)
  Format: '&f[&2$group&f] &e%p&f: &c%m' # The chat format
#
WarpSystem: # The warp system config, to disable see DisableCommands
  Message: true # If true, a message will appear when the user warps
  Effect: true # If true a particle effect will appear when the user warps
#
Others: # Uncategorized features here.
  DisableRain: false # If true, the weather changing will be disabled on your server.
  DoubleJump: true # If true, your players will be able to double jump!
  JumpPadBlock: REDSTONE_BLOCK # Jump Pad block. !!WARNING!! MUST BE A MATERIAL NAME.
  JumpPadEnabled: true # If true, JumpPad will be enabled
  KeepFood: true # If true, players will not starv.
  KeepHealth: true # If true, players will not take damage.
  Stacker: true # If true, the minigame stacker will be enabled.
  JoinItems: false # If true, the Item-Giving system will be enabled.
  JoinItemsChangeWorld: false # If the join items will be given on world change.
  JoinItemsDeath: false # If true, the player will receive the Join Items on death.
  ClearInventoryOnEveryWorld: false # If true the player inventory will be cleared on world change ( Every World )
  ClearInventory: false # If true the player inventory will be cleared upon join.
  NoDrops: true # If true, the player will not be able to drop items.
  NoDeathDrops: true # If true, the player will not drop items on death.
  AllowItemMove: false # If false, the player will not be able to move items on the inventory.
  AntiOP: false # If true this will remove every OP on the server every 15 seconds. 
  HubItems: true # If the command /hubitems will be enabled.
  StackerEnabledMessage: '&aStacker Enabled!' # The stacker enabled message.
  StackerDisabledMessage: '&cStacker Disabled!' # The stacker disabled message.
  FirstJoinItemsOnly: false # If true, the first join items will be only given on first join
  AllowBuilding: true # If false, players without permission will not be able to build on hub worlds.
#
DisabledCommands: # Here you add the commands you want to fully disable, 
- warp # This example will totally disable my /warp command
#
Worlds: # Here are listed the worlds that will have all the funcions enabled. ( Exclude the per-world ones )
- Example