name: HubBasics
version: 3.0
main: me.Fabricio20.Main
softdepend: [BarAPI]
commands:
  plugins:
    description: List the server plugins.
    aliases: pl
  hub:
    description: Teleports you back to hub.
  lobby:
    description: Teleports you back to hub.
  sethub:
    description: Sets the Hub location
  hat:
    description: Changes your hat!
  hb:
    description: HubBasics.
  uuid:
    description: Get someones UUID.