name: HubBasics
version: 3.0.5
main: me.Fabricio20.Main
softdepend: [BarAPI, PermissionsEx]
commands:
  plugins:
    description: List the server plugins.
    aliases: pl
  hub:
    description: Teleports you back to hub.
  lobby:
    description: Teleports you back to hub.
  sethub:
    description: Sets the Hub location
  hat:
    description: Changes your hat!
  hb:
    description: HubBasics.
  uuid:
    description: Get someones UUID.
  hubitems:
    description: Give you the hub items.
  stacker:
    description: Enable/Disable stacker.
  setwarp:
    description: Create a warp.
  warp:
    description: Warp.
  delwarp:
    description: Removes a warp.
  warps:
    description: List Warps.