main: net.notfab.hubbasics.HubBasics
version: 5.0-DEVELOPMENT
name: HubBasics
authors: [Fabricio20, Mister_2]
description: >
             HubBasics is a plugin containing settings, options and features you as a server owner might desire
commands:
  holograms:
    description: Manage holograms
  hat:
    description: Changes your hat
  hub:
    description: Go to hub
  sethub:
    description: Set hub location