# Welcome to HubBasics Bungee Config
#
# There is basically not a lot to do here, this plugin just adds a /lobby command
# that works globally.
#
# Lobby Server
# Either a string with the name of a server (that is configured on BungeeCord)
# or a list of strings for HubBasics to balance between.
Lobby: Lobby