ADVANCED_MOTD:
  Enabled: true
  Motds:
    - This is a default motd
    - Please change it
    - In the HubBasics
    - Config file
  Switchrate: 2
ANTI_VOID:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
  Location: Default
AUTOMATED_BROADCASTS:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
  Messages:
    - This is the first broadcast message
    - This is the second one
  Random: true
  Switchrate: 30
BOSSBAR_MESSAGES:
  Enabled: true
    Worlds:
      - world
      - world_the_end
      - world_nether
    Messages:
      - This is the first bossbar message
      - This is the second one
    Random: true
    Switchrate: 30
    Color: BLUE
    Style: SOLID
CONNECTION_MESSAGES:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
DOUBLE_JUMP:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
  Sound: ENTITY_BAT_TAKEOFF
  Force: 0.3
  Effect: null
FIXED_WEATHER:
  Enabled: false
  Worlds:
    - world
    - world_the_end
    - world_nether
JOIN_TELEPORT:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
  Location: Default
JUMP_PADS:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
  Sound: ENTITY_BAT_TAKEOFF
  Force: 5.0
  Material: IRON_BLOCK
  PressurePlate: true
KEEP_FOOD:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether
KEEP_HEALTH:
  Enabled: true
  Worlds:
    - world
    - world_the_end
    - world_nether