main: net.notfab.hubbasics.spigot.HubBasics
version: 6.9.1
name: HubBasics
authors: [Fabricio20]
softdepend: [Multiverse-Core, PlaceholderAPI]
api-version: 1.13
load: POSTWORLD
description: >
             HubBasics is a plugin containing settings, options and features you as a server owner might desire.
commands: